CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT INTO olx_states (id, last_crawled, url, state) VALUES
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-sp/sao-paulo-e-regiao', 'SP'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-mg', 'MG'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-es', 'ES'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-rj', 'RJ'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-ma', 'MA'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-pi', 'PI'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-ce', 'CE'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-rn', 'RN'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-pb', 'PB'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-pe', 'PE'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-al', 'AL'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-se', 'SE'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-ba', 'BA'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-ac', 'AC'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-am', 'AM'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-rr', 'RR'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-ro', 'RO'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-pa', 'PA'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-ap', 'AP'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-to', 'TO'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-mt', 'MT'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-go', 'GO'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-df', 'DF'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-ms', 'MS'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-pr', 'PR'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-sc', 'SC'),
(uuid_generate_v4(), null, 'https://www.olx.com.br/autos-e-pecas/carros-vans-e-utilitarios/estado-rs', 'RS');
